const char SSL_CERT_CRT[] = R"=====(
-----BEGIN CERTIFICATE-----
MIIBgTCCASugAwIBAgIUYLRs4pgRijC4ndx0W6yd4CAA6tEwDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKVWJlck1heWhlbTAeFw0yNDEyMjcxMzQwMDdaFw0yOTEy
MjYxMzQwMDdaMBUxEzARBgNVBAMMClViZXJNYXloZW0wXDANBgkqhkiG9w0BAQEF
AANLADBIAkEA3xyJsKmr2qBbbef2DUBueyaGoesTwnciu1EFte9XbfbeIO1Srg5Z
udGhAhNANAtZ9DRVIUHWGa2K7mcddS1/OwIDAQABo1MwUTAdBgNVHQ4EFgQUbCfX
zYWboWFiE3agrqE8LFtz1iQwHwYDVR0jBBgwFoAUbCfXzYWboWFiE3agrqE8LFtz
1iQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAANBAGBgciLnYmnCzdE+
7AdxQ2m4Q0G2CtVjA9LRfUht9e7lmxk5S7BfsbBPQNai1s9HQokeJ+rTtUOP3W/e
N9+KYJ0=
-----END CERTIFICATE-----
)=====";